global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Xml;
global using System.Xml.Serialization;
global using XMLLoader.Data;
global using XMLLoader.Models;
global using XMLLoader.Services;
